cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${LOG_DIR}")
if(COMPILER_ID STREQUAL "MSVC")
  set(flags /nologo /std:c++latest /Zc:__cplusplus /Zs /DHAS_STD_LIB=1)
  set(include_flag /I)
  set(define_flag /D)
else()
  set(flags -std=c++23 -DHAS_STD_LIB=1 -fsyntax-only)
  set(include_flag -I)
  set(define_flag -D)
endif()
foreach(directory IN LISTS INCLUDE_DIRS)
  if(NOT directory STREQUAL "")
    list(APPEND flags "${include_flag}${directory}")
  endif()
endforeach()

# CASE 0: historical pins 5-8. CASE 1: two independent steppers.
# CASE 2: duplicate pin in one stepper. CASE 3: overlapping modules.
foreach(case IN ITEMS 0 1 2 3)
  execute_process(COMMAND "${CXX}" ${flags} "${define_flag}CASE_ID=${case}" "${CASE_SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/case-${case}.log" "${output}${errors}")
  if(case LESS 2)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Valid stepper claim case ${case} failed:\n${output}${errors}")
    endif()
  elseif(NOT result MATCHES "^[1-9][0-9]*$" OR
      NOT "${output}${errors}" MATCHES "(static assertion failed|static_assert failed)[^\n]*Application has resource conflict")
    message(FATAL_ERROR "Expected stepper pin conflict for case ${case}, got ${result}:\n${output}${errors}")
  endif()
endforeach()
message(STATUS "Stepper pin probes: two valid applications and two expected conflicts passed")
