if(NOT COMMAND catch_discover_tests)
  find_package(grevir-test-support CONFIG REQUIRED)
endif()
set(stepper_runtime_sources stepper_test.cpp)
if(TARGET grevir::encoder)
  list(APPEND stepper_runtime_sources combine_test.cpp)
endif()
add_executable(grevir_stepper_runtime ${stepper_runtime_sources})
target_link_libraries(grevir_stepper_runtime PRIVATE grevir::stepper Catch2::Catch2WithMain)
if(TARGET grevir::encoder)
  target_link_libraries(grevir_stepper_runtime PRIVATE grevir::encoder)
  target_compile_definitions(grevir_stepper_runtime PRIVATE GREVIR_STEPPER_HAS_ENCODER=1)
endif()
set_target_properties(grevir_stepper_runtime PROPERTIES CXX_EXTENSIONS OFF)
catch_discover_tests(grevir_stepper_runtime TEST_PREFIX "stepper."
  PROPERTIES LABELS "stepper" TIMEOUT 10)
